### ISSUE TITLE
Reformatting Reblogged Fan Mail

### ISSUE THREAD

**Issue by Joyananda** [ShadeLotus/tumblr-template-sass#68]
see: http://gaming-thrones.tumblr.com/post/100562948405/do-you-ship-vulpes-inculta-with-anyone

The link is what the post looks like now. Below is a picture of what the post looks like when it's on the main feed.

![formatting](https://cloud.githubusercontent.com/assets/7832132/10106526/3eb22d5a-6383-11e5-9b38-b708ba5f0528.jpg)

**Comment by ShadeLotus** [comment]
styles adjusted, please verify @Joyananda
